 
services:
  dns:
    build: 
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "8053:53/udp"

  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80/tcp"
    depends_on:
      - tiago
    networks:
      - asa-network

  tiago:
    build: 
      context: ./www
      dockerfile: Dockerfile
    container_name: www
    networks:
      - asa-network

  mail:
    build: 
      context: ./mail
      dockerfile: Dockerfile
    container_name: mail
    networks:
      - asa-network

#Docker Networks
networks:
  asa-network:
    driver: bridge